export const events = [
  {
    id: "1",
    title: "React Summit 2023",
    description:
      "Join us for the biggest React conference of the year. Learn from industry experts, network with fellow developers, and discover the latest trends in React development.",
    date: "2023-06-15",
    time: "9:00 AM - 5:00 PM",
    location: "San Francisco",
    type: "conference",
    image: "/images/techups 1.jpg",
    isFeatured: true,
    tags: ["React", "JavaScript", "Web Development"],
  },
  {
    id: "2",
    title: "Introduction to Next.js",
    description:
      "Learn the basics of Next.js in this beginner-friendly workshop. We'll cover routing, data fetching, and deployment.",
    date: "2023-06-20",
    time: "2:00 PM - 4:00 PM",
    location: "Online",
    type: "webinar",
    image: "/images/techups 2.jpg",
    isFeatured: false,
    tags: ["Next.js", "React", "Beginners"],
  },
  {
    id: "3",
    title: "AI Hackathon: Build the Future",
    description:
      "A 48-hour hackathon focused on building AI-powered applications. Join teams from around the world to compete for prizes and recognition.",
    date: "2023-07-10",
    time: "10:00 AM",
    location: "New York",
    type: "hackathon",
    image: "/images/techups 3.jpg",
    isFeatured: true,
    tags: ["AI", "Machine Learning", "Hackathon"],
  },
  {
    id: "4",
    title: "Advanced TypeScript Workshop",
    description:
      "Take your TypeScript skills to the next level with this hands-on workshop. Learn advanced types, generics, and best practices.",
    date: "2023-06-25",
    time: "1:00 PM - 5:00 PM",
    location: "Chicago",
    type: "workshop",
    image: "/images/techups 4.jpg",
    isFeatured: false,
    tags: ["TypeScript", "JavaScript", "Advanced"],
  },
  {
    id: "5",
    title: "Building Accessible Web Applications",
    description:
      "Learn how to make your web applications accessible to everyone. This workshop covers ARIA, keyboard navigation, and testing tools.",
    date: "2023-07-05",
    time: "11:00 AM - 1:00 PM",
    location: "Online",
    type: "webinar",
    image: "/images/techups 5.jpg",
    isFeatured: false,
    tags: ["Accessibility", "Web Development", "UX"],
  },
  {
    id: "6",
    title: "DevOps Summit 2023",
    description:
      "A conference dedicated to DevOps practices, tools, and culture. Learn from industry leaders and connect with the DevOps community.",
    date: "2023-08-15",
    time: "9:00 AM - 6:00 PM",
    location: "Seattle",
    type: "conference",
    image: "/images/techups 1.jpg",
    isFeatured: true,
    tags: ["DevOps", "CI/CD", "Cloud"],
  },
  {
    id: "7",
    title: "Mobile App Development Bootcamp",
    description:
      "An intensive bootcamp on mobile app development using React Native. Build cross-platform apps for iOS and Android.",
    date: "2023-07-20",
    time: "9:00 AM - 4:00 PM",
    location: "Austin",
    type: "workshop",
    image: "/images/techups 3.jpg",
    isFeatured: false,
    tags: ["React Native", "Mobile Development", "iOS", "Android"],
  },
  {
    id: "8",
    title: "Web3 and Blockchain Fundamentals",
    description:
      "Get started with Web3 development in this introductory webinar. Learn about blockchain, smart contracts, and decentralized applications.",
    date: "2023-06-30",
    time: "3:00 PM - 5:00 PM",
    location: "Online",
    type: "webinar",
    image: "/images/techups 2.jpg",
    isFeatured: false,
    tags: ["Web3", "Blockchain", "Ethereum"],
  },
  {
    id: "9",
    title: "Cybersecurity Hackathon",
    description:
      "Test your security skills in this competitive hackathon. Identify vulnerabilities, exploit weaknesses, and secure systems.",
    date: "2023-08-05",
    time: "10:00 AM",
    location: "Boston",
    type: "hackathon",
    image: "/images/techups 5.jpg",
    isFeatured: true,
    tags: ["Cybersecurity", "Ethical Hacking", "Network Security"],
  },
]
